package com.dev.vault.model.domain.user.jwt;

import com.dev.vault.model.domain.user.User;
import com.dev.vault.model.enums.TokenType;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Entity for saving JWT token that has been generated by registration and or authentication/login.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document
public class JwtToken {

    @Id
    private String jwtTokenId;

    private String token;
    private TokenType type;
    private boolean expired;
    private boolean revoked;

    /* relationships */
    @Transient
    private User user;
    /* end of relationships */

}
